apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: s3-sidecar-high-priority-nonpreempting
value: 1000000000 # sidecar has the highest possible user-defined priority (may be evicted by system-cluster-critical (2000000000), system-node-critical (2000001000)), it will free up resources shortly after user pod was evicted from the node
preemptionPolicy: Never # new sidecar won't preempt already running pods
globalDefault: false
---
apiVersion: v1
kind: Pod
metadata:
  name: s3-sidecar-podid-volumeid
  namespace: kube-system # must be the same as for serviceAccount
spec:
  priorityClassName: s3-sidecar-high-priority-nonpreempting
  nodeName: ip-192-168-15-75.eu-west-1.compute.internal # or ip-192-168-91-88.eu-west-1.compute.internal
  restartPolicy: Never
  serviceAccountName: s3-csi-driver-sa
  containers:
    - name: s3-mountpoint
      securityContext:
        privileged: true
      image: 151381207180.dkr.ecr.eu-west-1.amazonaws.com/s3-csi-driver-sidecar:latest
      command:
        - mount-s3
      args:
        - s3-csi-driver # bucket
        - /var/lib/kubelet/pods/32e2058c-1b8e-4b47-a849-dbc20306c8e9/volumes/kubernetes.io~csi/s3-pv/mount
        - --foreground
        - --debug
        - --allow-other
        - --uid=1001
        - --gid=2002
      volumeMounts:
        - name: kubelet-dir
          mountPath: /var/lib/kubelet
          mountPropagation: "Bidirectional"
  volumes:
    - name: kubelet-dir
      hostPath:
        path: /var/lib/kubelet
        type: Directory
