apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  persistentVolumeReclaimPolicy: Retain # PV can not be used after deletion of PVC, recreation of PV is required
  capacity:
    storage: 1200Gi # ignored, required
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  mountOptions:
    - uid=1001
    - gid=2002
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: s3-csi-driver # bucket name, required
---
apiVersion: v1
kind: PersistentVolumeClaim # single PVC may be used by multiple pods
metadata:
  name: s3-claim
spec:
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # required for static provisioning
  resources:
    requests:
      storage: 10Gi # ignored, required
  volumeName: s3-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: s3-app
spec:
  securityContext:
    runAsUser: 1001
    runAsGroup: 2002
  containers:
    - name: app
      image: centos
      command: ["/bin/sh"]
      args: ["-c", "echo 'Hello from the container!' >> /data/$(date -u).txt; tail -f /dev/null"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: s3-claim